### ISSUE TITLE
broken link :  https://github.com/LordNoteworthy/cpu-internals/blob/master/pdf/VMCS.pdf

### ISSUE THREAD

**Issue by Martins3** [LordNoteworthy/cpu-internals#1]
> -  The VMCS layout is available in a form of table here: [VMCS Layout.pdf](https://github.com/LordNoteworthy/cpu-internals/blob/master/pdf/VMCS.pdf)

**Comment by ayoubfaouzi** [comment]
Sorry for my late answer, fixed.
